"""Create tables

Revision ID: b4fb0fb3fa77
Revises: 
Create Date: 2025-09-16 19:53:11.991995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4fb0fb3fa77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('books_id', sa.Integer(), nullable=False),
    sa.Column('books_title', sa.String(length=80), nullable=False),
    sa.Column('books_author', sa.String(length=80), nullable=True),
    sa.Column('books_image', sa.String(length=255), nullable=True),
    sa.Column('books_info_url', sa.String(length=255), nullable=True),
    sa.Column('books_genre', sa.String(length=80), nullable=True),
    sa.Column('books_publication_date', sa.Date(), nullable=True),
    sa.Column('books_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('books_id')
    )
    op.create_table('users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('users_username', sa.String(length=80), nullable=False),
    sa.Column('users_email', sa.String(length=80), nullable=False),
    sa.Column('users_password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('users_id'),
    sa.UniqueConstraint('users_email'),
    sa.UniqueConstraint('users_username')
    )
    op.create_table('users_books',
    sa.Column('userbooks_id', sa.Integer(), nullable=False),
    sa.Column('userbooks_user_id', sa.Integer(), nullable=False),
    sa.Column('userbooks_book_id', sa.Integer(), nullable=False),
    sa.Column('userbooks_read', sa.Boolean(), nullable=False),
    sa.Column('userbooks_rating', sa.Integer(), nullable=True),
    sa.Column('userbooks_note', sa.Text(), nullable=True),
    sa.Column('userbooks_finished_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['userbooks_book_id'], ['books.books_id'], ),
    sa.ForeignKeyConstraint(['userbooks_user_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('userbooks_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_books')
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###
